#!/bin/bash
# List files in current directory in long format, including hidden files
ls -la

# Change directory to parent directory and list files in long format, including hidden files
cd ..
ls -la

# List files in /boot directory in long format, including hidden files
ls -la /boot
