#!/bin/bash
cwd=$(pwd)
parent_dir=$(dirname "$cwd")
for file in "$cwd"/*.html; do
  filename=$(basename "$file")
  dest_file="$parent_dir/$filename"
  if [[ ! -e "$dest_file" ]] || [[ "$file" -nt "$dest_file" ]]; then
    cp "$file" "$parent_dir"
    echo "Copied $filename to $parent_dir"
  else
    echo "Skipped $filename, already exists in $parent_dir and is up to date"
  fi
done
#!/bin/bash
find . -name "*.html" -type f -exec cp -n -t ../ {} +
